
FROM bde2020/spark-master:3.0.0-hadoop3.2

# Install neo4j-spark-connector
RUN wget https://github.com/neo4j-contrib/neo4j-spark-connector/releases/download/4.1.5/neo4j-connector-apache-spark_2.12-4.1.5_for_spark_3.jar && \
    mv neo4j-connector-apache-spark_2.12-4.1.5_for_spark_3.jar /spark/jars/

ENV NEO4J_CONNECTOR_JAR=/spark/jars/neo4j-connector-apache-spark_2.12-4.1.5_for_spark_3.jar